version: '3.8'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /root/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - waline_network

  waline:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "8360:8360"
    environment:
      TZ: ${TZ}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PREFIX: ${MYSQL_PREFIX}
      SITE_NAME: ${SITE_NAME}
      DISABLE_AUTHOR_NOTIFY: ${DISABLE_AUTHOR_NOTIFY}
      DISABLE_REGION: ${DISABLE_REGION}
      DISABLE_USERAGENT: ${DISABLE_USERAGENT}
      LOGIN: ${LOGIN}
      LEVELS: ${LEVELS}
      OAUTH_URL: ${OAUTH_URL}
      WALINE_ADMIN_MODULE_ASSET_URL: ${WALINE_ADMIN_MODULE_ASSET_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LIMITER_POINT: ${LIMITER_POINT}
      LIMITER_DURATION: ${LIMITER_DURATION}
      LIMITER_BLOCK_DURATION: ${LIMITER_BLOCK_DURATION}
      IPQPS: 0
    networks:
      - waline_network
    volumes:
      - ${PWD}/data:/app/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - waline_network
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - /root/volumes/redis:/data
    environment:
      TZ: ${TZ}
    ports:
      - "6379:6379"   # expose only if you need host access
    networks:
      - waline_network

networks:
  waline_network:
    driver: bridge

volumes:
  mysql_data:
    external: true
